import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../../Components/context/ThemeContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    'google-adsense-account': 'ca-pub-1752210907408525',
  },
  verification: {
    google: 'AUeF-Uo5_N8q50uPzSt_083GHFoCg9zRzmaY8z-YCbU',
  },
};


export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
       <body className="min-h-full flex flex-col">
      <ThemeProvider>
        {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
